service: smsAnnoyer

custom:
  delay: ${opt:delay, '15'} 

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  region: ${opt:region, 'eu-west-1'}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action: "SNS:Publish"
      Resource:
        - "*"

functions:
  handle:
    name: smsAnnoyer-${self:provider.stage}
    description: "Sends an SMS to ${opt:recipient} every ${self:custom.delay} minutes"
    handler: handler.handle
    timeout: 10
    environment:
      MESSAGE: ${opt:message}
      RECIPIENT: ${opt:recipient}
    events:
      - schedule:
          rate: rate(${self:custom.delay} minutes)